### ISSUE TITLE
프리미엄 기능 뭐할지 알려주세요

### ISSUE THREAD

**Issue by sihyeokpark** [1-EXON/ComIn#3]
알려주면 상줌

**Comment by piquark6046** [comment]
네트워크 통신을 사용하여, **스마트폰** 전면에 컴퓨터 **하드웨어**의 정보 표시 기능

**Comment by sihyeokpark** [comment]
**판톼스틕** 하지만 저는 네크워트 통신기능을 **몰라요**
쨌든 알려드렸으니 도움을 주신 분에 추가를(?)

**Comment by ditto7890** [comment]
Google, Amazon, Samsung, Microsoft 를 원하빈다

**Comment by muno9748** [comment]
이건 C# 프로젝트지만 Node.js로 서버를 만들어서
핸드폰에서 브라우저로 컴터 IP로 접속하면 socket.io로 계속 socket통신으로 하드웨어 정보 갱신을 해주면 될거같은데요
~~헤헿 Node.js 조아~~
node.js에도 쉘 커맨드를 실행하는 child_process가 있으니까
C#에도 child_process같은게 있겠죠
그니까 child_process 같은걸로 npm start를 하면 끝
음 근데 너무 어렵나

**Comment by muno9748** [comment]
대충 npm하고
폴더 만든 다음에
```csharp
System.Diagnostics.Process process = new System.Diagnostics.Process();
System.Diagnostics.ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo();
startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;
startInfo.FileName = "cmd.exe";
startInfo.Arguments = "/c shell node ./폴더명/script.js";
process.StartInfo = startInfo;
process.Start();
```
이런식으로 하면 될거같은데

**Comment by piquark6046** [comment]
> 이건 C# 프로젝트지만 Node.js로 서버를 만들어서
> 핸드폰에서 브라우저로 컴터 IP로 접속하면 socket.io로 계속 socket통신으로 하드웨어 정보 갱신을 해주면 될거같은데요
> ~~헤헿 Node.js 조아~~
> node.js에도 쉘 커맨드를 실행하는 child_process가 있으니까
> C#에도 child_process같은게 있겠죠
> 그니까 child_process 같은걸로 npm start를 하면 끝
> 음 근데 너무 어렵나

컴퓨터에서 웹 서버를 여는 것 보다는 두 기기끼리 앱의 특수 프로트콜로 통신해서 데이터를 송수신하는 것이 더 낫지 않을까요?

**Comment by muno9748** [comment]
WebSocket 통신?

**Comment by piquark6046** [comment]
> WebSocket 통신?

아마도요.

**Comment by piquark6046** [comment]
@1-EXON issue 좀 닫아주세요.

**Comment by sihyeokpark** [comment]
넵
